### ISSUE TITLE
Can not refresh configuration file

### ISSUE THREAD

**Issue by luozhouyang** [SpongeNobody/Clashy#23]
**Describe the bug**

**To Reproduce**
1. Go to 'Profiles'
2. Click on 'Refresh'
3. See error

**Expected behavior**
Refresh the configuration file

**Screenshots**
Unknown error!
![clashy](https://user-images.githubusercontent.com/34032031/74927195-211e4d80-5412-11ea-9315-8c24ee27382a.png)

**Environment (please complete the following information):**
 - OS: Linux
 - OS version: 16.04
 - Distribution (if needed): Ubuntu
 - Clashy Version: 0.1.12

**Additional context**

**Comment by SpongeNobody** [comment]
Refreshing a profile means re-download it from your service provider. 

Seems like you are creating a customized profile since your profile name is 'gnode.yaml' rather than something like 'www.yourserviceprovider.com_subscription_id=1234.yaml'. So the refresh button does not work in this scenario.

If you want to keep your renamed/copied/self-created profile up-to-date, you need to edit another configuration file manually, which is `clashy-configs/subscriptions.json`. This configuration file tracks mapping between your local file and subscription URL.

If you just want to enable this profile, just click on the checkmark.

Closing this issue for now. Feel free to re-open it if you have more questions.

Thanks for the feedback.
