### ISSUE TITLE
Archlinux包 discord 依赖？和无法运行？

### ISSUE THREAD

**Issue by CosmosAtlas** [SpongeNobody/Clashy#49]
**Describe the bug**
The archlinux package in [release v0.1.16](https://github.com/SpongeNobody/Clashy/releases/tag/v0.1.16) has dependency `discord` and after installation won't run

**To Reproduce**
### Discord dependency
1. Download the file `clashy-0.1.16-x86_64-arch-linux.pkg.tar.zst`
2. Run `# pacman -U clashy-0.1.16-x86_64-arch-linux.pkg.tar.zst`

```shell
> sudo pacman -U clashy-0.1.16-x86_64-arch-linux.pkg.tar.zst
[sudo] password for cosmos:
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (5) discord-0.0.10-3  libappindicator-gtk3-12.10.0-14  libindicator-gtk3-12.10.1-9
             opera-ffmpeg-codecs-83.0.4103.97-1  clashy-0.1.16-1

Total Download Size:     0.07 MiB
Total Installed Size:  337.73 MiB

:: Proceed with installation? [Y/n]
```

### Won't run
After accepting to install, running `clashy` nothing happens. 
```
> clashy

> 
```
**Expected behavior**
1. Why would this depend on `discord`?
2. `clashy` should show up. 

**Environment (please complete the following information):**
 - OS: Archlinux
 - OS version: 5.7.5-arch1-1
 - Clashy Version 0.1.16

## Additional comments
1. `clashy` does exist as a process after the command runs.

**Comment by SpongeNobody** [comment]
Archlinux build was provided by [Arch-Jason](https://github.com/Arch-Jason) and may have some issues since it's converted from `deb` package (see #48 )

I haven't made an "official" Arch build due to I've been busy other stuff (life's hard. sign.) since v0.1.14 released.

Arch Linux build is a little different since it seems to contain a built-in electron distribution and will cause some issues during the package. Or I did it the wrong way.

I will try to fix this ASAP.

Also, any PRs / suggestions are welcome.

Thanks for your contribution.

**Comment by skykeyjoker** [comment]
You can try to download and install this package from AUR。

**Comment by CosmosAtlas** [comment]
Thanks for creating the packages on AUR @skykeyjoker 

I've since figured out how to set up Clash and use its proxies on Linux and no longer need a Clash client. 

PS: someone tagged the `clashy-bin` out of date on AUR on Aug. 19, 2020. You might wanna bump the version.

**Comment by skykeyjoker** [comment]
Thank you for your reply, I will update the software package as soon as possible.
(ﾉ)`ω´(ヾ) ​​​

在 2020-08-20 13:35:02，CosmosAtlas <notifications@github.com> 写道：


Thanks for creating the packages on AUR @skykeyjoker

I've since figured out how to set up Clash and use its proxies on Linux and no longer need a Clash client.

PS: someone tagged the clashy-bin out of date on AUR on Aug. 19, 2020. You might wanna bump the version.

**Comment by Arch-Jason** [comment]
Oh no! I just knew your reply today. Sorry I was careless. I used debtap to convert it and I didn't check the final package.
I noticed that someone made a archlinux packge and uploaded to AUR, so you can remove my terrible package from releases page....(╥_╥)
本蒟蒻再次向各位道歉(。・_・。)
