### ISSUE TITLE
在树莓派上可以直接运行吗？

### ISSUE THREAD

**Issue by hucstar** [SpongeNobody/Clashy#64]
我在ubuntu上一直在用clashy，不知在树莓派上可否流畅运行，Clashy_0.1.19_amd64.deb，应该是不行，不支持64吧？Clashy-0.1.19.AppImage我也试了，貌似也不成功，可以给点建议吗？原谅我是树莓派新手。

**Comment by SpongeNobody** [comment]
Theoretically, yes.

You might need to compile `clashy` by yourself for raspberry pi. See [this](https://stackoverflow.com/questions/57813389/how-do-i-build-and-install-an-electron-app-for-raspbian-using-appimage) for more details.

Also you need to modify `pre-build.js` to download arm based `clash` binary.

I didn't make an arm based release because I don't own devices like that thus I can't test `clashy` on them 🤣
